"""Structured audit envelopes, independent of provider transcripts."""
from dataclasses import dataclass, field
from enum import StrEnum
from uuid import uuid4
from .domain import now


class EventType(StrEnum):
    TASK_READY = 'TASK_READY'
    TASK_ASSIGNED = 'TASK_ASSIGNED'
    TASK_COMPLETED = 'TASK_COMPLETED'
    TASK_FAILED = 'TASK_FAILED'
    TASK_CANCELLED = 'TASK_CANCELLED'
    AGENT_STARTED = 'AGENT_STARTED'
    AGENT_COMPLETED = 'AGENT_COMPLETED'
    AGENT_FAILED = 'AGENT_FAILED'
    CONTEXT_SELECTED = 'CONTEXT_SELECTED'
    MESSAGE_SENT = 'MESSAGE_SENT'
    MESSAGE_DELIVERED = 'MESSAGE_DELIVERED'
    MESSAGE_REJECTED = 'MESSAGE_REJECTED'
    RETRY_SCHEDULED = 'RETRY_SCHEDULED'
    TASK_BLOCKED = 'TASK_BLOCKED'
    TASK_REQUEST_ADMITTED = 'TASK_REQUEST_ADMITTED'
    TASK_REQUEST_REJECTED = 'TASK_REQUEST_REJECTED'
    WORK_STOPPED = 'WORK_STOPPED'
    GROUP_CLOSED = 'GROUP_CLOSED'
    RECORD_CHANGED = 'RECORD_CHANGED'
    RUN_CREATED = 'RUN_CREATED'
    ROLE_ASSIGNED = 'ROLE_ASSIGNED'
    TASK_CREATED = 'TASK_CREATED'
    FINDING_CREATED = 'FINDING_CREATED'
    FINDING_CRITIQUED = 'FINDING_CRITIQUED'
    FINDING_VALIDATED = 'FINDING_VALIDATED'
    FINDING_REJECTED = 'FINDING_REJECTED'
    FINDING_INVALIDATED = 'FINDING_INVALIDATED'
    FINDING_SUPERSEDED = 'FINDING_SUPERSEDED'
    REVIEW_STARTED = 'REVIEW_STARTED'
    REVIEW_COMPLETED = 'REVIEW_COMPLETED'
    REVIEW_REJECTED = 'REVIEW_REJECTED'
    KNOWLEDGE_PROMOTED = 'KNOWLEDGE_PROMOTED'
    KNOWLEDGE_REMOVED = 'KNOWLEDGE_REMOVED'
    CONSOLIDATION_COMPLETED = 'CONSOLIDATION_COMPLETED'
    CONFLICT_OPENED = 'CONFLICT_OPENED'
    CONFLICT_RESOLVED = 'CONFLICT_RESOLVED'
    PROPAGATION_SELECTED = 'PROPAGATION_SELECTED'
    CROSS_POLLINATION = 'CROSS_POLLINATION'
    PROPAGATION_DELIVERED = 'PROPAGATION_DELIVERED'
    PROPAGATION_SKIPPED = 'PROPAGATION_SKIPPED'
    PROPAGATION_RETRACTED = 'PROPAGATION_RETRACTED'
    RETRACTION_DELIVERED = 'RETRACTION_DELIVERED'
    RECONSIDERATION_STARTED = 'RECONSIDERATION_STARTED'
    RECONSIDERATION_COMPLETED = 'RECONSIDERATION_COMPLETED'
    CYCLE_STARTED = 'CYCLE_STARTED'
    CYCLE_COMPLETED = 'CYCLE_COMPLETED'
    BRANCH_PROGRESS = 'BRANCH_PROGRESS'
    BRANCH_TERMINATED = 'BRANCH_TERMINATED'
    COVERAGE_GAP = 'COVERAGE_GAP'
    RUN_STATE_CHANGED = 'RUN_STATE_CHANGED'
    SYNTHESIS_GATE_EVALUATED = 'SYNTHESIS_GATE_EVALUATED'
    SYNTHESIS_STARTED = 'SYNTHESIS_STARTED'
    SYNTHESIS_STALE = 'SYNTHESIS_STALE'
    RESULT_CREATED = 'RESULT_CREATED'
    RESULT_REJECTED = 'RESULT_REJECTED'
    FINAL_REVIEW_STARTED = 'FINAL_REVIEW_STARTED'
    FINAL_REVIEW_COMPLETED = 'FINAL_REVIEW_COMPLETED'
    FINAL_REVIEW_STALE = 'FINAL_REVIEW_STALE'
    RESULT_REVISION_REQUESTED = 'RESULT_REVISION_REQUESTED'
    REPAIR_WORK_CREATED = 'REPAIR_WORK_CREATED'
    RUN_COMPLETED = 'RUN_COMPLETED'
    RUN_EXHAUSTED = 'RUN_EXHAUSTED'
    RUN_FAILED = 'RUN_FAILED'
    RUN_CANCELLED = 'RUN_CANCELLED'
    EXECUTION_STARTED = 'EXECUTION_STARTED'
    EXECUTION_COMPLETED = 'EXECUTION_COMPLETED'
    EXECUTION_FAILED = 'EXECUTION_FAILED'
    EXECUTION_CANCELLED = 'EXECUTION_CANCELLED'
    PROVIDER_REQUESTED = 'PROVIDER_REQUESTED'
    PROVIDER_COMPLETED = 'PROVIDER_COMPLETED'
    PROVIDER_FAILED = 'PROVIDER_FAILED'
    TOOL_STARTED = 'TOOL_STARTED'
    TOOL_COMPLETED = 'TOOL_COMPLETED'
    TOOL_FAILED = 'TOOL_FAILED'
    OUTPUT_REJECTED = 'OUTPUT_REJECTED'


@dataclass(frozen=True, kw_only=True)
class EventDraft:
    type: EventType
    id: str = field(default_factory=lambda: str(uuid4()))
    timestamp: str = field(default_factory=now)
    schema_version: int = 1
    record_id: str | None = None
    record_revision: int | None = None
    task_id: str | None = None
    agent_id: str | None = None
    assignment_id: str | None = None
    role_id: str | None = None
    group_id: str | None = None
    causation_id: str | None = None
    correlation_id: str | None = None
    detail_json: str = '{}'


@dataclass(frozen=True, kw_only=True)
class Event(EventDraft):
    run_id: str
    sequence: int
